### PR TITLE
Maint/cpp 11 updates

### PR DESCRIPTION
**Pull request by JWhitleyAStuff**
Designed to be merged after #56. General clean-up. Adding lots of `constexpr`. Reducing code duplication and unnecessary global copies of publishers and subscribers.

- [x] Tested in Vehicle

### CODE REVIEW

**Comment by JWhitleyAStuff** [comment]
Tested in Lexus RX 450h.

**Comment by JWhitleyAStuff** [comment]
Sorry, @mlemm99 - Can you review again? I forgot to update the copyrights.

**Comment by JWhitleyAStuff** [comment]
Thanks!

**Comment by jilinzhouas** [comment]
Currently the code is publishing a lot of ros topics. Can we provide some mechanisms to enable/disable some ros topics in the future?

**Comment by JWhitleyAStuff** [comment]
@jilinzhouas - I agree. Please create an Enhancement issue on this repo.

**Pull request merged**
