### PR TITLE
chore: update lifecycle api

### PR DESCRIPTION
**Pull request by wep21**
update to the latest rclcpp_lifecycle api.

### CODE REVIEW

**Comment by icolwell-as** [comment]
Thanks @wep21, can you provide a link to some documentation about `ManagedEntityInterface`? I can't seem to find much. Is `ManagedEntityInterface` available in ROS2 Foxy?

**Comment by wep21** [comment]
@icolwell-as 
> can you provide a link to some documentation about ManagedEntityInterface? 

This comes from https://github.com/ros2/rclcpp/pull/1863

> Is ManagedEntityInterface available in ROS2 Foxy?

No, I built this with ros2 rolling on Ubuntu22.04. This PR is a preparation for humble.

**Comment by icolwell-as** [comment]
@wep21, thanks for the info. I will leave this PR open until we decide to release on Humble.

**Comment by wep21** [comment]
@icolwell-as I enabled build on both foxy and humble. Could you proceed to merge this PR?
Also is it possible to prepare pre-release repositry to put astuff ros packages for `humble`?

**Comment by icolwell-as** [comment]
Hi @wep21, there's no need to have both foxy and humble builds at the same time on the master branch. Feel free to remove the `#ifdef`s so that only humble is supported.
In general, our master branches represent the latest ROS release, so now that humble is almost released, I've created a `foxy` branch such that the `ros2_master` branch can target humble.

Unfortunately we don't support any pre-release repos, but some time after humble is officially released, we will add `ros-humble-pacmod3` to our `https://s3.amazonaws.com/autonomoustuff-repo/`.

**Comment by wep21** [comment]
@icolwell-as 

> there's no need to have both foxy and humble builds at the same time on the master branch. Feel free to remove the #ifdefs so that only humble is supported.

I got it. I reverted backward support.

> some time after humble is officially released, we will add ros-humble-pacmod3 to our https://s3.amazonaws.com/autonomoustuff-repo/.

Thanks. We also need `pacmod3_msgs` and `kvaser_interface`, so could you also add these packages into your repository?

**Comment by wep21** [comment]
@icolwell-as Now, humble has been released. Please let me know if astuff humble packages are also available.

**Comment by icolwell-as** [comment]
Hi @wep21, thanks for the update. At the moment I am targeting the end of next week (June 3rd) for Humble pacmod and kvaser packages. Since Humble is a long-term release we want to test in-vehicle before releasing.
Let me know if this timeline doesn't work for you. 
Thanks!

**Comment by wep21** [comment]
@icolwell-as 

> At the moment I am targeting the end of next week (June 3rd) for Humble pacmod and kvaser packages.

It's no problem for us. Thanks for letting me know the release plan.

**Review by icolwell-as — APPROVED** [review]
Tested yesterday.

**Review by dvangeyn-as — APPROVED** [review]

**Comment by icolwell-as** [comment]
@wep21: pacmod3, pacmod3_msgs, kvaser_interface, and pacmod_game_control are now released on humble.

**Pull request merged**
